<add>(CI) check rare string for CI
FISCO-BCOS/console pull request #785
Opened 2023-08-01 03:02 UTC by LucasLi1024

2023-08-01 04:35 UTC, bxq2011hust approved these changes

2023-08-01 11:10 UTC, kyonRay requested changes

2023-08-01 11:10 UTC, kyonRay commented on .ci/check_rare_string.sh
> +            LOG_ERROR "error: check failed, the md5 values of rareString and eventLogsFromSet are not equal, fail concatenatedString: ${concatenatedString}"
should exit 1 when error occurs

2023-08-01 11:23 UTC, LucasLi1024 commented on .ci/check_rare_string.sh
> +            LOG_ERROR "error: check failed, the md5 values of rareString and eventLogsFromSet are not equal, fail concatenatedString: ${concatenatedString}"
fixed

2023-08-02 07:39 UTC, kyonRay approved these changes

2023-08-02 07:59 UTC, merged